image: docker

services:
  - docker:dind

build:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH .
    - docker push registry.gitlab.com/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME
