image: docker

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH .

push:
  stage: push
  script:
    - docker push registry.gitlab.com/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME
